from sqlalchemy import Column
from sqlalchemy.dialects.mysql import MEDIUMINT, INTEGER, TINYINT, SMALLINT, VARCHAR, DATETIME, BOOLEAN, DATE, FLOAT
from models.sqla_utils import PLAYOFFBASE

class Player(PLAYOFFBASE):
    __tablename__ = 'Player'

    player_id = Column(VARCHAR(8), primary_key=True)
    player_name = Column(VARCHAR(50))
    team = Column(VARCHAR(3), primary_key=True)
    year = Column(INTEGER(4), primary_key=True)
    PA = Column(INTEGER(4))
    AB = Column(INTEGER(4))
    S = Column(INTEGER(3))
    D = Column(INTEGER(3))
    T = Column(INTEGER(3))
    HR = Column(INTEGER(3))
    TB = Column(INTEGER(3))
    H = Column(INTEGER(3))
    R = Column(INTEGER(3))
    RBI = Column(INTEGER(3))
    SB = Column(INTEGER(3))
    CS = Column(INTEGER(3))
    BB = Column(INTEGER(3))
    SO = Column(INTEGER(3))
    HBP = Column(INTEGER(3))
    SF = Column(INTEGER(3))
    SH = Column(INTEGER(3))
    AVG = Column(FLOAT(5))
    OBP = Column(FLOAT(5))
    SLG = Column(FLOAT(5))
    OPS = Column(FLOAT(5))
    BF = Column(INTEGER(4))
    IP = Column(FLOAT(5))
    Ha = Column(INTEGER(4))
    HRa = Column(INTEGER(4))
    TBa = Column(INTEGER(4))
    BBa = Column(INTEGER(4))
    IBBa = Column(INTEGER(3))
    K = Column(INTEGER(3))
    HBPa = Column(INTEGER(3))
    BK = Column(INTEGER(3))
    W = Column(INTEGER(2))
    L = Column(INTEGER(2))
    SV = Column(INTEGER(2))
    TR = Column(INTEGER(3))
    ER = Column(INTEGER(3))
    RA = Column(FLOAT(4))
    ERA = Column(FLOAT(4))

